<<<<<<< HEAD
remote_theme: mmistakes/minimal-mistakes

=======
theme: jekyll-theme-tactile
>>>>>>> 2d4d7974d198f60b725fb4210267b71ff6276a94

title: [Concurso Av. Bernardo Monteiro]
description: [EQUIPE CERNE]

